### PR TITLE
Added Viewing Feedbacks

### PR DESCRIPTION
**Pull request by simarsingh24**
First steps for issue #1377 
Changes: Added Viewing Submitted Feedbacks
Screenshots for the change: 
screenshot_20180331-113400

### CODE REVIEW

**Comment by simarsingh24** [comment]
I would be including posting feedback (using a FAB) in this PR only, Ignore indentation errors for now. @iamareebjamal is this a good way to show feedbacks?

**Comment by simarsingh24** [comment]
I would be including posting feedback (using a FAB) in this PR only, Ignore indentation errors for now. @iamareebjamal is this a good way to show feedbacks?

**Comment by iamareebjamal** [comment]
Instead show a rating bar and quote style comments

**Comment by iamareebjamal** [comment]
And don't use cards

**Comment by simarsingh24** [comment]
@iamareebjamal i will first finish the posting part and then make these UI related changes

**Comment by simarsingh24** [comment]
@iamareebjamal the body for posting feedback is

 ```
   "links": {
        "self": "/v1/feedbacks/38"
    },
    "jsonapi": {
        "version": "1.0"
    },
    "data": {
        "links": {
            "self": "/v1/feedbacks/38"
        },
        "id": "38",
        "type": "feedback",
        "attributes": {
            "rating": "5",
            "comment": "Great event."
        },
        "relationships": {
            "user": {
                "links": {
                    "related": "/v1/feedbacks/38/user",
                    "self": "/v1/feedbacks/38/relationships/user"
                }
            },
            "event": {
                "links": {
                    "related": "/v1/feedbacks/38/event",
                    "self": "/v1/feedbacks/38/relationships/event"
                }
            }
        }
    }
}
```


how should i add this to the post request method?
i am thinking of creating a body class for this like 
```
data class PostFeedbackBody(
		val links: Links,
		val jsonapi: Jsonapi,
		val data: Data
)

data class Data(
		val links: Links,
		val id: String,
		val type: String,
		val attributes: Attributes,
		val relationships: Relationships
)

data class Attributes(
		val rating: String,
		val comment: String
)

data class Relationships(
		val user: User,
		val event: Event
)

data class User(
		val links: Links
)

data class Links(
		val related: String,
		val self: String
)

data class Event(
		val links: Links
)

data class Links(
		val related: String,
		val self: String
)

data class Links(
		val self: String
)

data class Jsonapi(
		val version: String
)

data class Links(
		val self: String
)
```

**Comment by ParthivMangukiya** [comment]
@simarsingh24 we are using JsonApiConverter library that will generate json API spec 1 standard post request automatically for you.
https://github.com/jasminb/jsonapi-converter

**Comment by simarsingh24** [comment]
@parthivmangukiya this is what the plugin generates, i think there will be a better way to do it?

**Comment by ParthivMangukiya** [comment]
IMO we have already included JsonApiConverter factory in retrofit, you just need to create POJO for feedback and the rest of the things will be handled by the library. If you want, you can also customize the behavior using annotations.

**Comment by iamareebjamal** [comment]
What @ParthivMangukiya said. Look at any other POJO. All have the same syntax, GET or POST

**Comment by simarsingh24** [comment]
```
@Data
@Type("feedback")
@Builder()
@NoArgsConstructor
@AllArgsConstructor
@JsonNaming(PropertyNamingStrategy.KebabCaseStrategy.class)
public class PostFeedbackBody extends RealmObject {

    @PrimaryKey
    @Id(IntegerIdHandler.class)
    private int id;
    private String comment;
    private String rating;
    private User user;
    @Relationship("event")
    private Event event;



}
```
is this right? for 
```
{
  "data": {
    "type": "feedback",
    "relationships": {
      "event": {
        "data": {
          "type": "event",
          "id": "1"
        }
      },
      "user": {
        "data": {
          "type": "user",
          "id": "77"
        }
      }
    },
    "attributes": {
      "rating": "5",
      "comment": "Great event."
    }
  }
}
```

**Comment by ParthivMangukiya** [comment]
There should be Relationship annotation in User.
I'm not sure but we could use the same POJO for get and post by using JSONIgnore property and provide only access for serialize to Event.

**Comment by iamareebjamal** [comment]
Rather than relationship in user, add user in feedback

**Comment by iamareebjamal** [comment]
We will use same POJO, it'll work

**Comment by simarsingh24** [comment]
```Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.```
I am getting this error on passing User and Event @ParthivMangukiya @iamareebjamal can someone help me how to create copy of these and then pass it to the function

```
   compositeDisposable.add(APIClient.getOpenEventAPI().postFeedback(PostFeedbackBody.builder().event(event)
                .rating(rating).comment(comment).user(user).build())
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(feedback -> {
                            Timber.d("Posted successfully");
                            postFeedbackResponse.setValue(FeedbackFragmentViewModel.VALID);
                       
                        },
                        throwable -> {
                            Timber.d(throwable.toString());
                           
                            Timber.d("Post unsuccessful");
                            postFeedbackResponse.setValue(FeedbackFragmentViewModel.INVALID);
                        }));
```

**Comment by iamareebjamal** [comment]
1. Rename PostFeedbackBody to Feedback
2. realm.copyFromRealm(feedback);

**Comment by simarsingh24** [comment]
@iamareebjamal what i did 
```
Feedback feedback = Feedback.builder().event(event).rating(rating).comment(comment).user(user).build())
```

```
 Realm realm = Realm.getDefaultInstance();
        realm.copyFromRealm(feedback);
```
but i am getting this error
```
Only valid managed objects can be copied from Realm.
```

**Comment by iamareebjamal** [comment]
https://stackoverflow.com/questions/30318521/retrofit-post-realm-object

**Comment by simarsingh24** [comment]
@iamareebjamal I apologise for the delay but I am a little busy with university tutorial exams and practicals, It may take some time to finish this

**Comment by simarsingh24** [comment]
Will be creating two separate PR's for viewing and posting part, closing this!

**Pull request closed without merging**
