### PR TITLE
feat : enhance bookmark widget

### LINKED ISSUE #1816: Enhance the bookmark widget
**Actual Behaviour**

1. The UI is not in sync with the bookmarks UI in app.
2. The bookmarks dont show more than one bookmarks in the widget.
3. No option to remove bookmark.

**Expected Behaviour**

The bookmark widget should be in total sync with app bookmark.

**Screenshots of the issue**

screenshot_2017-07-13-20-14-38-047_com miui home

**Would you like to work on the issue?**

Yes.

**Target Milestone to solve the issue**

[milestone 10](https://github.com/fossasia/open-event-android/milestone/33)

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes #1816

Changes: 
- Removes bullets
- Changes colour of widget title
- Adds a divider
- Fixes the bug of incomplete bookmark title in the listview.

Screenshots for the change: 

screenshot_2017-07-16-01-55-52-122_com miui home

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
@iamareebjamal @arp95 @mahikaw @shreyasnbhat @Shailesh351 please review.

**Review by shreyasnbhat — APPROVED** [review]

**Comment by mahikaw** [comment]
I'm not sure why exactly, but the app seems to be crashing for me everytime I make a widget. Is anyone else facing this? @Shailesh351 @shreyasnbhat @rohanagarwal94 @arp95

**Comment by rohanagarwal94** [comment]
@mahikaw yes, it is crashing. Hence I have submitted the PR [1815](https://github.com/fossasia/open-event-android/pull/1815) for that.

**Review by mahikaw — APPROVED** [review]

**Comment by arp95** [comment]
@rohanagarwal94 then we should merge that pr first.

**Review by arp95 — APPROVED** [review]
LGTM.

**Comment by Shailesh351** [comment]
@rohanagarwal94 Looks good. Font size of date and time is almost same as Session title. It should be little less than the font size of session title.

**Comment by rohanagarwal94** [comment]
@Shailesh351 updated.

**Review by Shailesh351 — APPROVED** [review]

**Pull request merged**
