### PR TITLE
Fix #2158 - Improve UI of comments for feed.

### LINKED ISSUE #2158: Improve UI of comments for feed
**Actual Behaviour**

The current UI for feed can be improved by giving proper dimensions of width and height.

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fixes #2158 

Changes: Add a number for no of comments and shift position of date.

Screenshots for the change: 
image

image

### CODE REVIEW

**Comment by dr0pdb** [comment]
@mayank8318 Can we add a card for each comment ? It would look better. What do you think ?

**Comment by mayank8318** [comment]
@srv-twry Nice suggestion! I will try and post a screenshot. Lets see how it looks.

**Comment by mayank8318** [comment]
Should I go with a solid background for the card?

**Comment by dr0pdb** [comment]
Let's try both the solid and the transparent one also.

**Comment by mayank8318** [comment]
image

image

image

@srv-twry @iamareebjamal Some combinations that I tried.

**Comment by iamareebjamal** [comment]
The second one looks good IMO

**Comment by mayank8318** [comment]
@iamareebjamal Applied the second one.

**Comment by iamareebjamal** [comment]
Sorry for getting to it too late, can you please remove border and transparency as well?

**Comment by mayank8318** [comment]
@iamareebjamal Looks like this now :
image

**Comment by iamareebjamal** [comment]
I think we can remove the card and just have a divider

**Comment by mayank8318** [comment]
Changes :
image

**Comment by iamareebjamal** [comment]
Lighten the divider to light grey please

**Comment by mayank8318** [comment]
Changes :
image

**Comment by mayank8318** [comment]
@iamareebjamal I think you need to update or restart Codacy?

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
