### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by riyapannu7**
Article 'the' missing in the phrase "logo of event"

Fixes #[Add issue number here. Note: This will automatically close the issue. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@riyapannu7 Please follow best practices and link an issue to the PR 😄

**Comment by the-dagger** [comment]
Hi, @riyapannu7 Please go ahead and open an issue for any fix/feature you would like to implement in the app.
Only after the issue has been created, open a pull request and mention the issue it refers to in the Pull Request body.

**Comment by riyapannu7** [comment]
Ok, thank you so much.

**Comment by riyapannu7** [comment]
@the-dagger Okay, thank you so much.

**Comment by dr0pdb** [comment]
@riyapannu7 Kindly link the issue you have created using  [fixes #issuenumber]. Also fetch the updated development branch and rebase your working branch.

**Comment by iamareebjamal** [comment]
@riyapannu7 Status?

**Pull request closed without merging**
