### PR TITLE
Fix #2315 - Use threaded asynchronous transaction using separate Real…

### LINKED ISSUE #2315: Use threaded asynchronous transaction using separate Realm instance - eventDates
**Actual Behaviour**

Presently the transaction is done using the global realm object.

**Expected Behaviour**

Use a local realm instance for a threaded asynchronous transaction.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
…m instance.

Fixes #2315 

Changes: Use a separate realm instance for the transaction.

### CODE REVIEW

**Comment by mayank8318** [comment]
@iamareebjamal Is this what you meant?

**Review by iamareebjamal — APPROVED** [review]
Yes, but check that app is working correctly everywhere

**Comment by mayank8318** [comment]
Working for me. @srv-twry @simarsingh24 @nikit19 Can you confirm?

**Comment by simarsingh24** [comment]
@mayank8318 working fine for me too 👍

**Pull request merged**
