### PR TITLE
fix : Event bar slides down smoothly (#1925)

### PR DESCRIPTION
**Pull request by dreadpool2**
Changes: 
The event bar slides down smoothly.
videotogif_2017 09 26_01 52 07

### CODE REVIEW

**Comment by scandindian** [comment]
@dreadpool2 Please squash all your commits with a proper message.

**Comment by dreadpool2** [comment]
@heysadboy Sir, actually I am new to open source and dont know for some reasons squashing of commits is not properly happening . I am sorry for any inconvenience caused! &#128517;

**Comment by scandindian** [comment]
@dreadpool2 Use `git rebase -i HEAD~x` where x is the number of commits, that is 40 in this case. 
Then to squash, all commits after first, let the first one remain pick,
And change all subsequent ones to be squash, like

```
pick f87uey65
squash iu8976g
squash tre34s2b
squash tr22nshg
squash oiu765qj
...
```
Then save it, a new prompt will open with several commit messages, delete all except first and save
Now, you have to force push it to your branch as the history has changed

`git push -f origin_branch your_branch_name`

In future maybe you should do this before making a pull request. A few are okay but 40 commits are way too big for us to analyze for a small code. :-)

**Comment by heysadboy** [comment]
@dreadpool2 Use `git rebase -i HEAD~x` where x is the number of commits, that is 40 in this case. 
Then to squash, all commits after first, let the first one remain pick,
And change all subsequent ones to be squash, like

```
pick f87uey65
squash iu8976g
squash tre34s2b
squash tr22nshg
squash oiu765qj
...
```
Then save it, a new prompt will open with several commit messages, delete all except first and save
Now, you have to force push it to your branch as the history has changed

git push -f origin_branch your_branch_name

In future maybe you should do this before making a pull request. A few are okay but 40 commits are way too big for us to analyze for a small code. :-)

**Comment by dreadpool2** [comment]
@heysadboy Thank you so much ! Its very considerate of yours!

**Pull request closed without merging**
