### PR TITLE
Fix #2172: session speaker designation text

### LINKED ISSUE #2172: Fix issue with the Speakers info in SessionDetailsActivity
**Actual Behaviour**

The details about the Speaker in SessionDetailsActivity is partially hidden.

**Expected Behaviour**

It shouldn't be hidden.

**Screenshots of the issue**

screenshot_2018-01-19-19-47-06-81

Here, the word "Brave Software" which should be shown below the Speaker's name and image isn't shown properly, only "Brave" is shown, "software" is partially hidden.

**Would you like to work on the issue?**

~~Yes~~
No
To be done by beginners(Less than 5 commits in this project).

### PR DESCRIPTION
**Pull request by omkarprabhu-98**
Fixes #2172 

Changes: Added lines, max lines, singleLine attributes to item_session_speaker.xml for speakers_list_designation text view  

Screenshots for the change: 
screenshot_20180131-230925 1

screenshot_20180131-230940 1

screenshot_20180131-231017 1

@srv-twry please take a look. Kindly inform me for any further changes.

### CODE REVIEW

**Review by mayank8318 — APPROVED** [review]

**Comment by omkarprabhu-98** [comment]
@iamareebjamal, @mayank8318  should I do any more changes to the branch?

**Review by iamareebjamal — APPROVED** [review]

**Comment by mayank8318** [comment]
@omkarprabhu-98 Can you please squash the commits into a single commit? Incase you need help squashing or have any doubts, feel free to ask :)

**Comment by omkarprabhu-98** [comment]
```
git reset --soft HEAD~3

git commit -m "fix: session speaker designation text"

git push git push origin +fix
```
@mayank8318 These would do it, right ?

**Comment by dr0pdb** [comment]
The last line looks weird. Force push in the last line :+1:

**Comment by omkarprabhu-98** [comment]
Thanks @srv-twry but,
I am having a confusion, when I checked fix branch in the my forked repo 

The following highlighted commits by @iamareebjamal  and my commit on Feb 1 should have been there, right?
Please help me, I don't understand how to rectify this!
Sorry for the trouble  
  
commit

**Comment by iamareebjamal** [comment]
No problem, I will squash using github

You can learn about squashing by creating a test repo and a branch :)

**Pull request merged**
