### PR TITLE
fix : No progress indication on clicking retry when feed refresh fails in Live Feed

### LINKED ISSUE #2106: No progress indication on clicking retry when feed refresh fails in Live Feed
**Actual Behaviour**

Hitting retry when Live Feed fails to load feed doesn't give any indication of retrying. Also, the swipeRefresh's refreshing inside LiveFeed doesn't stop even after  "Couldnt Refresh" snack message is displayed.

**Expected Behaviour**

Some progress animation should be displayed to the user and swipeRefreshLayout's refreshing should stop when Refresh is failed.

**Steps to reproduce it**

Stoping swipeRefreshLayout's refreshing inside downloadFeed() under throwable section.
Turning on the swipeRefreshLayout's refreshing animation on clicking snackbar's retry.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by simarsingh24**
Fixes #2106

Changes: Made swipeRefreshLayout's state refreshing on clicking Snackbar's retry button.

### CODE REVIEW

**Comment by dr0pdb** [comment]
@simarsingh24 Please attach screenshot/GIF whenever possible. In this case you should attach a GIF showing the change.

**Comment by simarsingh24** [comment]
@srv-twry Ill keep that in mind... 
Before changes gif-
videotogif_2018 01 09_13 37 47

After changes gif- 
change -1 hitting retry now shows swipeLayouts refresh animation
change -2 swipe and refresh of layout stops after the snackbar message is displayed (earlier it never stopped)
videotogif_2018 01 09_13 41 59

**Review by S2606 — COMMENTED** [review]
@simarsingh24 Instead of SwipeRefreshLayout, why not add the same previous progress dialog??

**Comment by simarsingh24** [comment]
@s2606 then that dialog box will be displayed every time you use swipe to refresh

**Comment by S2606** [comment]
@simarsingh24 But as per the gif, refresh action takes place from snackbar

**Comment by simarsingh24** [comment]
@S2606  if you hit retry on snackbar then that swipeLayout refrehing sign is displyed, if you lokk closely at the gif same thing happens if you swipe down the layout to refresh. And i think opening a dialog everytime you click on retry wont look nice?

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
