### PR TITLE
fix: show download button when apk available

### LINKED ISSUE #1819: Showing download button only when the apk is available
**Actual Behaviour**

Currently showing of the download button in the apk-generator when the apk isnt available. Show download button only when apk is available.

**Expected Behaviour**

Doing above changes.

**Steps to reproduce it**

-

**LogCat for the issue**

-

**Screenshots of the issue**

-

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

https://github.com/fossasia/open-event-android/milestone/33

### PR DESCRIPTION
**Pull request by arp95**
Fixes #1819 

Changes: 
shows download button only when apk available.

Screenshots for the change: 

-

@iamareebjamal @shreyasnbhat @Shailesh351 @rohanagarwal94 
please review.

### CODE REVIEW

**Comment by arp95** [comment]
guys please review

**Comment by mahikaw** [comment]
@arp95 Maybe I'm wrong, but I think that it was better when the download was just disabled. That way the user that comes there for the first time atleast knows that there's a download button. Let's wait for other's to give their opinions. :)
And could also look at what codacy's suggesting and incorporate that as well.

**Comment by arp95** [comment]
@mahikaw please have a look at web app generator. i think its better to shiw download button only when apk is available. 
guys provide your views.

**Comment by niranjan94** [comment]
I agree with mahika on this. This allows the user to know that he/she will
be able to download after the generation is complete. Otherwise the user
will be left clueless as to how the app will be sent to him/her until the
long generation process completes.

In webapp, the time taken for generation is much shorter. But android it
would take quite sometime. So my vote is for how it is now. Showing a
download button (but disabled) such that the user has an idea of what is to
come.

**Comment by arp95** [comment]
@niranjan94 
umm fine. then should i close this then?

**Comment by arp95** [comment]
closing this then.

**Pull request closed without merging**
