### PR TITLE
fix : Update speaker model and sample json for JSONAPI

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes Part of #1680 

Changes: 
- Updated `Speaker` model and `speakers` json file according to jsonapi-response

### CODE REVIEW

**Comment by Shailesh351** [comment]
@arp95 @mahikaw @rohanagarwal94 @iamareebjamal @shreyasnbhat Please review.

Also @arp95 @mahikaw Update samples in https://github.com/fossasia/open-event :+1:

**Comment by arp95** [comment]
@Shailesh351 yes already updating the samples according to the new api with the script.

**Comment by Shailesh351** [comment]
@arp95 Speakers JSON file is remaining :sweat_smile: https://github.com/fossasia/open-event/blob/master/sample/FOSSASIA16/speakers

**Comment by arp95** [comment]
yes speakers one wasnt done because it wasnt decided at that time. updating it so that we have a sample to work with the latest api.

**Review by iamareebjamal — CHANGES_REQUESTED** [review]
Update DB version

**Comment by Shailesh351** [comment]
@iamareebjamal @arp95 @mahikaw @rohanagarwal94 @shreyasnbhat Please review.

**Review by iamareebjamal — APPROVED** [review]

**Review by mahikaw — APPROVED** [review]

**Comment by Shailesh351** [comment]
@the-dagger @mananwason Please review and merge

**Pull request merged**
