### PR TITLE
refactor: Pull configuration into strategies

### LINKED ISSUE #2309: Remove configuration from Application File
Split configuration into modules and strategies

### PR DESCRIPTION
**Pull request by iamareebjamal**
Fixes #2309 

Changes: 
- Move configuration into individual strategies

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@srv-twry @mayank8318 @simarsingh24 @jindalAnuj @shivaraju07 @jindalAnuj Please test the app and check if there are any errors

**Comment by iamareebjamal** [comment]
@srv-twry @mayank8318 @simarsingh24 @nikit19 @jindalAnuj @shivaraju07 Please test the app and check if there are any errors

**Comment by jindalAnuj** [comment]
working fine in my device

**Comment by mayank8318** [comment]
Working on my device too :)

**Comment by nikit19** [comment]
Works just as expected in my device too :+1:

**Comment by simarsingh24** [comment]
No issues on my device too! 👍

**Comment by shivaraju07** [comment]
Works fine 👍

**Comment by simarsingh24** [comment]
@iamareebjamal what about the issues highlighted by codacybot?

**Comment by shivaraju07** [comment]
I think these functions throws exception.

**Comment by iamareebjamal** [comment]
@simarsingh24  `what about the issues highlighted by codacybot?` These say that we should end tests in asserts. Codacy doesn't know that tests usually don't contain asserts in not using JUnit

We are using Mockito here

**Pull request merged**
