### PR TITLE
fix: travis build workaround with api 27

### LINKED ISSUE #2322: Fix travis ci build
**Actual Behaviour**

Currently the Travis CI build fails.
This issue has been registered before for version 27.0.2 and i think it should be the same problem as this one. 
1. [First](https://github.com/travis-ci/travis-ci/issues/8874)
2. [Second](https://github.com/travis-ci/travis-ci/issues/8651)

**Expected Behaviour**

It should build properly.

**Steps to reproduce it**

Open a PR.

**LogCat for the issue**
```

FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 27.0.3].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Would you like to work on the issue?**

Yes.

@iamareebjamal Please review the above links and also the build logs of my PR #2320 in order to confirm that it is the same issue.

### PR DESCRIPTION
**Pull request by dr0pdb**
Fixes #2322 

Changes: Fix travis ci build with API 27 using the workaround mentioned [here](https://github.com/travis-ci/travis-ci/issues/8874)

Screenshots for the change: NA

@iamareebjamal Please review.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
I think changing `ANDROID_BUILD_TOOLS_VERSION=27.0.1` to `ANDROID_BUILD_TOOLS_VERSION=27.03` should work

**Comment by dr0pdb** [comment]
@iamareebjamal , please review.

**Comment by iamareebjamal** [comment]
Was this needed? `yes | sdkmanager "platforms;android-27"`

Try without this

**Comment by dr0pdb** [comment]
@iamareebjamal Yeah it works.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
