### PR TITLE
feat: Add menu item for displaying information in SpeakersCall object #1937 

### LINKED ISSUE #1937: Add menu item for displaying information present in SpeakersCall object of event class
**Actual Behaviour**

There is no menu option for displaying SpeakersCall object values.

**Expected Behaviour**

There should be a overflow menu option for displaying the information in a dialog.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AkshayCHD**
Fixes #1937 

Changes: Now there exists an overflow menu option in the main activity that displays the information of SpeakersCall object in the form of a dialog box, when it is clicked.

Screenshots for the change: 
screenshot_1507650592
screenshot_1507651203

### CODE REVIEW

**Comment by AkshayCHD** [comment]
@iamareebjamal sir please review

**Comment by manav-mj** [comment]
@AkshayCHD I think you should add the menu-items in `menu_home` inflated in `AboutFragment` instead of making a new menu for `MainActivity`

**Comment by AkshayCHD** [comment]
@iamareebjamal sir i made the changes as per the latest commits please see my changes

**Review by iamareebjamal — APPROVED** [review]

**Comment by manav-mj** [comment]
This PR also Fixes #1947

**Pull request merged**
