### PR TITLE
fix : Travic CI always passing issue

### LINKED ISSUE #1902: Travis CI not failing
**Actual Behaviour**

Currently Travis CI is always passing build.
https://travis-ci.org/Shailesh351/open-event-android/builds/268397568

**Expected Behaviour**

It should fail when there is error. 

**LogCat for the issue**

```
BUILD FAILED
Total time: 18.741 secs
The command "./generate_apks.sh" exited with 0.
```

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 17](https://github.com/fossasia/open-event-android/milestone/40)

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1902 

Changes:
- Fix Travic CI always passing issue
- Remove unnecessary builds

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@Shailesh351 The `./gradlew build` can be skipped. Only assembleRelease is required

**Comment by Shailesh351** [comment]
@iamareebjamal Yes, there is unnecessary builds. IMO we should skip `./gradlew assembleRelease` and keep `./gradlew build` or use `./gradlew assembleDebug`

If we use `./gradlew assembleRelease`  then it will not generate debug builds which are being uploaded in the apk branch.

And also we will need to sign apps before we upload apks to apk branch.

**Comment by iamareebjamal** [comment]
Yeah, we should use `assembleDebug`

**Comment by Shailesh351** [comment]
I think we should use  `./gradlew build` for default FOSSASIA summit sample and `./gradlew assembleDebug` for other samples.

Using `./gradlew build` only one time will ensure that all the builds(debug and release) will be built without errors. 

What's your thought?

**Comment by iamareebjamal** [comment]
@Shailesh351 I agree 👍

**Comment by Shailesh351** [comment]
@iamareebjamal  Please review

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
