### PR TITLE
Fixes #2260 fixedProfileCrash added permission

### LINKED ISSUE #2260: app crash when pickingUp image from gallery
**Actual Behaviour**

App crashes when image is picked for profile

**Expected Behaviour**

App should not crash

**Steps to reproduce it**
go to login
click profile logo
pick a image 
tada app crashed .....

**LogCat for the issue**

`java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$3.done(AsyncTask.java:325)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
 at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=22827, uid=10533 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
 at android.os.Parcel.readException(Parcel.java:1684)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
 at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
 at android.content.ContentResolver.query(ContentResolver.java:534)
 at android.content.ContentResolver.query(ContentResolver.java:475)
 at com.yalantis.ucrop.util.FileUtils.getDataColumn(FileUtils.java:109)
 at com.yalantis.ucrop.util.FileUtils.getPath(FileUtils.java:183)
 at com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:171)
 at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:90)
 at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:41)
 at android.os.AsyncTask$2.call(AsyncTask.java:305)
 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 ... 4 more`

**Screenshots of the issue**

ezgif com-video-to-gif 3

**Would you like to work on the issue?**

Yes

### LINKED ISSUE #2304: Move to Sd card not enabled
**Actual Behaviour**

App Can't be moved to sd card

**Expected Behaviour**

App should move to sd card

**Steps to reproduce it**

go to app info it will hace move to sd card option not enabled 

**Screenshots of the issue**

image

**Would you like to work on the issue?**
yes

### PR DESCRIPTION
**Pull request by jindalAnuj**
Fixes #2260 . app crash when pickingUp image from gallery  e.g.  #2260 

Changes: [Permission added for picking image 
                 added     
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
and some code for checking android version in editprofileActivity

Screenshots for the change: 
ezgif com-video-to-gif 7

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Please break into separate PRs, a PR should only target one issue.

Secondly, there are some stylistic and coding issues, but we'll discuss them when PRs are separated

**Comment by jindalAnuj** [comment]
@iamareebjamal i am new to github so please guide me that how to make seperate pr

**Comment by jindalAnuj** [comment]
@iamareebjamal should  submit a new one for profile crash

**Comment by iamareebjamal** [comment]
Yes

**Comment by iamareebjamal** [comment]
@jindalAnuj Please resolve the requested changes

**Comment by jindalAnuj** [comment]
@iamareebjamal sorry i was  busy but will send requested changes in couple of hours

**Comment by jindalAnuj** [comment]
@iamareebjamal i have done the changes in second commit is it ok .I know it was done a long time ago but please review that

**Comment by jindalAnuj** [comment]
closing this and  submitted  #2345  pull request

**Pull request closed without merging**
