### PR TITLE
Fix #2005-Provide Ascending/Descending option in sorting.

### LINKED ISSUE #2005: Provide Ascending/Descending option in sorting
**Actual Behaviour**

Currently there is no option to select the order of sort (Ascending or Descending).

**Expected Behaviour**

There should be an option to select the order of sorting.

**Steps to reproduce it**

Open Schedule and click sort from the menu.

**Screenshots of the issue**

image

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by mayank8318**
Fixes #2005 

Changes: Add buttons to Sort dialog box for ascending / descending option.

Screenshots for the change: 
image

### CODE REVIEW

**Review by scandindian — CHANGES_REQUESTED** [review]
I think it would look more minimalistic if we use icon button instead of text for ascending and descending.

**Comment by mayank8318** [comment]
@heysadboy Didn't get you. You mean it should be a part of the `menu` ?

**Comment by scandindian** [comment]
@mayank8318 use image button instead of text. Like ↑ for ascending. What's your view about it?

**Comment by mayank8318** [comment]
@heysadboy Using Image Button in place of a text buttons in an alert dialog does't look intuitive for the user. Maybe we can use the arrows in the menu or something like in any normal website or sorting thing?
But I guess the text buttons looks better.

**Review by scandindian — APPROVED** [review]

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
