### PR TITLE
feat : Add User Profile feature

### LINKED ISSUE #1844: Add User profile feature
**Actual Behaviour**

After adding user authentication in app it will only show email and logout option in User Profile(https://github.com/fossasia/open-event-android/pull/1827).

**Expected Behaviour**

Add feature to show user name, links which will be fetched from server. Add feature to edit user profile.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**Would you like to work on the issue?**

Yes

**Target Milestone to solve the issue**

[Milestone 12](https://github.com/fossasia/open-event-android/milestone/35)

### PR DESCRIPTION
**Pull request by Shailesh351**
Fixes #1844 

Changes:
- [x] Add first name, last name and avatar in User profile layout
- [x] Fetch User data using token and identifier 
- [x] Add layout for updating profile
- [x] Add API service to make PATCH request to server for updating user data
- [x] Add swipe refresh layout to update info by swiping down 
- [x] Add changes confirmation on pressing back button
- [x] Add option to update Avatar
- [x] Add option to change password

### CODE REVIEW

**Comment by rohanagarwal94** [comment]
@shailesh351 please add a screenshot.

**Comment by Shailesh351** [comment]
@rohanagarwal94 Currently looks like this. I'll change UI after implementing main logic and feature.

[screenshot-1501394852587](https://user-images.githubusercontent.com/18264684/28751091-c60c25fc-751b-11e7-9cbe-8890e1df7329.jpg)

**Comment by rohanagarwal94** [comment]
I think it would be better if instead of a nav drawer item as a profile button, the top shelf of the nav drawer where the org logo exists, be changed to the user profile photo and the user gets directed to his profile on click.

**Comment by shreyasnbhat** [comment]
@Shailesh351 The profile edit photo would look better if it is circular.

**Comment by Shailesh351** [comment]
@shreyasnbhat @rohanagarwal94 Now looks like this

[UserProfile.gif](https://user-images.githubusercontent.com/18264684/28791671-ce06c50c-764a-11e7-876e-f970ce570d6f.gif)

**Comment by Shailesh351** [comment]
Now looks like this

[UserProfile.gif](https://user-images.githubusercontent.com/18264684/28860492-7ed96e5e-777a-11e7-9822-3ae16568b1c4.gif)

**Comment by Shailesh351** [comment]
Final demo here : https://www.youtube.com/watch?v=OHIoE9ExdiU

@iamareebjamal @shreyasnbhat @the-dagger @mananwason Please review

**Comment by the-dagger** [comment]
looks good 👍

**Review by the-dagger — APPROVED** [review]

**Pull request merged**
