### PR TITLE
Share Speaker Info

### PR DESCRIPTION
**Pull request by pgellert**
I did these changes according to the Google Code-In task (https://codein.withgoogle.com/dashboard/task-instances/6273876803715072/?sp-page=1), to share the speaker's name and email through an android intent.

### CODE REVIEW

**Comment by championswimmer** [comment]
Code builds. Tests are failing, that's why travis is red.

**Comment by championswimmer** [comment]
@mananwason code looks good to me

**Comment by mananwason** [comment]
@championswimmer code is fine. It's just the travis timeout issue. It's not able to upload the apks tp the emulators. We need to restart travis builds everytime

**Comment by mananwason** [comment]
@championswimmer it passed now by simply restarting!!

**Comment by mananwason** [comment]
But we shouldn't merge it right now, let's merge the best output after gci is over.

**Comment by mananwason** [comment]
@pgellert Closing this.

**Pull request closed without merging**
