### PR TITLE
fix: Improve the UI of SpeakerListFragment

### LINKED ISSUE #2149: Improve UI of ViewHolder in SpeakersList RecyclerView
**Actual Behaviour**

Currently the UI of ViewHolder is not good. The details of the Speaker is displayed on top of the Image of the Speaker. In some cases it leads to a problem as the face of the speaker is hidden completely by the description.

**Expected Behaviour**

The description shouldn't block the face of the speaker.

**Screenshots of the issue**

screenshot_2018-01-17-12-26-24-42
screenshot_2018-01-17-12-27-08-38

One can see that in case of Mr. Alex Curreton Griffiths in the first image and Mrs/Miss Anwesha Das in the second image, the description almost completely blocks the face which makes having the image useless.

**Would you like to work on the issue?**

Yes

**Proposed Changes**

I believe we can move the description below the image of the speaker to avoid this issue.
@iamareebjamal Views ?

### PR DESCRIPTION
**Pull request by dr0pdb**
Fixes #2149 

Changes: Converted to Staggered layout and using Palette to determine the background color.

Screenshots for the change: 

screenshot_2018-01-20-20-18-26-32
screenshot_2018-01-20-20-18-32-55
screenshot_2018-01-20-20-18-41-70

@iamareebjamal Please review.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@srv-twry The rounded edges and shadows have been lost, can you please revert them back. Also, headers are gone

**Comment by dr0pdb** [comment]
@iamareebjamal 
> Also, headers are gone

I'm not sure whether headers work with StaggeredGridLayout. Do they ?

**Comment by iamareebjamal** [comment]
They should, there's no reason they wouldn't

**Comment by iamareebjamal** [comment]
@srv-twry Any progress?

**Comment by dr0pdb** [comment]
I will finish this surely by tomorrow.

**Comment by dr0pdb** [comment]
@iamareebjamal There is an issue that i am facing. 
The sticky headers decoration has only been implemented for a LinearLayout only. I am trying to extend it to work for StaggeredGridLayout, but weirdly, the left and right columns are interchanged in the recycler view after the first row. Moreover the sticky headers doesn't look that good either. It blinks.

GIF:
videotogif_2018 01 24_20 10 41

Can you suggest something about what could go wrong specially with the inversion ? 

PS: I have removed the background color from palette for now. Will add it after i fix this issue.

**Comment by iamareebjamal** [comment]
Alright, remove the Sticky Headers as they are not implemented in Support Library

**Comment by dr0pdb** [comment]
Changes: Convert to Staggered layout
Remove sticky headers
Background of info using Palette.

Screens:
screenshot_2018-01-25-04-55-16-17
screenshot_2018-01-25-04-55-23-17
screenshot_2018-01-25-04-55-39-90


@iamareebjamal Please review.

**Comment by iamareebjamal** [comment]
Shadow is too much, reduce to 2dp please

**Comment by dr0pdb** [comment]
Reduced elevation to 2dp.

Screen:
screenshot_2018-01-25-05-41-25-73

@iamareebjamal Please review.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
