### PR TITLE
added feat: option to view and submit feedback

### PR DESCRIPTION
**Pull request by simarsingh24**
Inital steps for #1377

### CODE REVIEW

**Comment by simarsingh24** [comment]
@iamareebjamal  I was working on Submit Feedback part, could you please tell me what post request would be for submitting feedback under any event_id 
screen shot 2018-02-17 at 3 35 20 pm

In this screenshot, they have not used event_id anywhere

**Comment by iamareebjamal** [comment]
You are not viewing the request data format, you are looking at query section

**Comment by simarsingh24** [comment]
@iamareebjamal Just to check if `postFeedback` was working I added a post feedback request everytime the user clicks on the FAB, but this is not working, could you please help me out?

LOG CAT (after pressing FAB ):
` POST https://open-event-api.herokuapp.com/v1/feedbacks http/1.1 (91-byte body)
02-19 23:27:05.254 305-689/? W/audio_hw_utils: audio_extn_utils_update_stream_app_type_cfg: App type could not be selected. Falling back to default
02-19 23:27:05.254 305-689/? I/audio_hw_primary: select_devices Selected apptype: 69936
02-19 23:27:05.254 305-689/? D/ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 131, path =  0
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> send_asm_topology
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> send_adm_topology
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> send_audtable
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> send_audvoltable
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> send_afe_cal
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> send_hw_delay : acdb_id = 131 path = 0
02-19 23:27:05.255 305-689/? D/ACDB-LOADER: ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
02-19 23:27:05.256 305-689/? I/audio_hw_utils: audio_extn_utils_send_app_type_cfg app_type 69936, acdb_dev_id 131, sample_rate 48000
02-19 23:27:05.257 305-689/? D/audio_hw_primary: select_devices: done
02-19 23:27:08.416 305-689/? D/audio_hw_primary: out_standby: enter: stream (0xed144a00) usecase(1: low-latency-playback)
02-19 23:27:08.492 305-689/? D/hardware_info: hw_info_append_hw_type : device_name = speaker
02-19 23:27:08.649 285-285/? I/MSM-irqbalance: Decided to move IRQ57 from CPU1 [P:0] to CPU5 [P:1] (banned)
02-19 23:27:08.649 285-285/? I/MSM-irqbalance: Decided to move IRQ132 from CPU1 [P:0] to CPU5 [P:1] (banned)
02-19 23:27:08.650 285-285/? I/MSM-irqbalance: Decided to move IRQ195 from CPU1 [P:0] to CPU5 [P:1] (banned)
02-19 23:27:08.650 285-285/? I/MSM-irqbalance: Decided to move IRQ166 from CPU1 [P:0] to CPU5 [P:1] (banned)
02-19 23:27:08.650 285-285/? I/MSM-irqbalance: Decided to move IRQ215 from CPU1 [P:0] to CPU5 [P:1] (banned)
02-19 23:27:09.014 1361-1404/system_process I/GnssLocationProvider: WakeLock acquired by handleDownloadXtraData()
02-19 23:27:09.015 1361-28114/system_process E/GpsXtraDownloader: No XTRA servers were specified in the GPS configuration
02-19 23:27:09.015 1361-28114/system_process I/GnssLocationProvider: WakeLock acquired by sendMessage(11, 0, null)` 

The request body for posting feedback is : 
screen shot 2018-02-19 at 11 31 17 pm

**Comment by simarsingh24** [comment]
@iamareebjamal  can you help me with this?

**Comment by iamareebjamal** [comment]
You should use curl or Postman tools for testing REST API. Doing so using Android is counter intuitive

**Comment by simarsingh24** [comment]
@iamareebjamal i will complete this after my midsems

**Comment by iamareebjamal** [comment]
@simarsingh24 Status?

**Comment by simarsingh24** [comment]
@iamareebjamal just got back from everything, will complete it within a day or two

**Pull request closed without merging**
