### PR TITLE
[WIP]feat: Convert to zoomable imageviews

### LINKED ISSUE #1841: Make the image zoom in on click in the live feed
**Actual Behaviour**

The user cannot zoom in the pictures in the livefeed.

**Expected Behaviour**

The image should have functionality to allow zoom on click.

**Would you like to work on the issue?**

Yes. @iamareebjamal @the-dagger views?

**Target Milestone to solve the issue**

[milestone 12](https://github.com/fossasia/open-event-android/milestone/35)

### PR DESCRIPTION
**Pull request by rohanagarwal94**
Fixes #1841

Changes:

- Used PhotoView library for zoom

- Changed each file for uniform formatting across the project.

@iamareebjamal @Shailesh351 @shreyasnbhat is this fine? Shall I implement this for other imageviews too? The zoomed images are gesture enabled and zoomable.

Reference - https://github.com/chrisbanes/PhotoView

Screenshots for the change: 

videotogif_2017 07 31_02 03 57

### CODE REVIEW

**Comment by iamareebjamal** [comment]
@rohanagarwal94 There are several changes in this PR not relevant to the changes. This makes it extremely hard to review code. Please only reformat the code you have added

**Comment by iamareebjamal** [comment]
If you want to reformat code, please do so using another PR

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Comment by mariobehling** [comment]
Closing due to inactivity.

**Pull request closed without merging**
