### PR TITLE
Transition of speaker image(#1913)

### PR DESCRIPTION
**Pull request by dreadpool2**
First steps for issues #1913 

Changes: Smooth transition now occurs from speaker's image to its sole activity.

(I want to close the previous PR of this issue ! I had messed up the commits completely that time, inconvenience is regretted!)

### CODE REVIEW

**Comment by dreadpool2** [comment]
@iamareebjamal Please review!

**Review by m-murad — CHANGES_REQUESTED** [review]
@dreadpool2 
You need to squash the commits. Also follow the commit guidelines.

**Comment by dreadpool2** [comment]
I think I have squashed them @m-murad

**Comment by m-murad** [comment]
No you haven't

**Comment by dreadpool2** [comment]
But in the command line it showed it has been squashed! &#128517;

**Comment by dreadpool2** [comment]
I think I have done the squashing now!  @m-murad

**Comment by m-murad** [comment]
Yes you have.

**Review by iamareebjamal — APPROVED** [review]

**Pull request merged**
